### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by shksa** [eBay/skin-react#42]
`yarn add skin-react` doesnt show any errors in the terminal, but when i try to import the package i get a `Cannot find module 'skin-react' or its corresponding type declarations` error. I looked into my `node_modules` folder and found a `yarn-error.log` which tells me there was an error during installation. Im installing this in next.js app.

```
Arguments: 
  /Users/armontoya/.nvm/versions/node/v12.17.0/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js publish

PATH: 
  /usr/local/opt/openssl@1.1/bin:/usr/local/opt/ruby/bin:/Users/armontoya/.sdkman/candidates/kotlin/current/bin:/Users/armontoya/Documents/Arturo/google-cloud-sdk/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/armontoya/.nvm/versions/node/v12.17.0/bin:/usr/local/Cellar/tomcat/apache-tomcat-9.0.30/bin:/usr/local/Cellar/maven/3.6.3/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/armontoya/Library/Developer/flutter/bin

Yarn version: 
  1.22.4

Node version: 
  12.17.0

Platform: 
  darwin x64

Trace: 
  Error: canceled
      at Interface.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:137008:13)
      at Interface.emit (events.js:315:20)
      at Interface._ttyWrite (readline.js:866:16)
      at ReadStream.onkeypress (readline.js:205:10)
      at ReadStream.emit (events.js:315:20)
      at emitKeys (internal/readline/utils.js:335:14)
      at emitKeys.next (<anonymous>)
      at ReadStream.onData (readline.js:1133:36)
      at ReadStream.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
```

**Comment by shksa** [comment]
Is this package stable enough to use in a critical application?

**Comment by montoya332** [comment]
Updated build script , thank you for creating issue

**Comment by montoya332** [comment]
This is currently in Beta
